// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.20;

import "forge-std/Script.sol";
import "../contracts/CrystalVerifier.sol";

/**
 * @title DeployCrystalVerifier
 * @notice Foundry deployment script for the full-table CrystalVerifier prototype.
 *
 * @dev The full-table verifier is not the production direction. It stores
 *      512 KB of table data and should be treated as a compatibility prototype.
 *      Production work should use the compact component-table verifier.
 *
 * Usage:
 *   1. Generate table data:
 *      python sdk/crystal_committer.py export-tables --output tables.json
 *
 *   2. Deploy:
 *      forge script script/Deploy.s.sol --rpc-url $RPC_URL --broadcast
 *
 *   3. Initialize tables (separate tx per head due to gas limits):
 *      Run the InitializeTables script below.
 */
contract DeployCrystalVerifier is Script {
    function run() external {
        uint256 deployerKey = vm.envUint("PRIVATE_KEY");

        vm.startBroadcast(deployerKey);

        CrystalVerifier verifier = new CrystalVerifier();

        vm.stopBroadcast();

        console.log("CrystalVerifier deployed to:", address(verifier));
        console.log("Owner:", verifier.owner());
        console.log("Next: initialize tables with InitializeTables script");
    }
}

/**
 * @title InitializeTables
 * @notice Initialize crystal tables from exported JSON.
 *
 * Usage:
 *   VERIFIER_ADDRESS=0x... forge script script/Deploy.s.sol:InitializeTables \
 *     --rpc-url $RPC_URL --broadcast
 *
 * Note: This is a full-table prototype initializer. It is not a production gas
 * estimate and should not be used as evidence of deployability. Prefer compact
 * component-table initialization for production verifier work.
 */
contract InitializeTables is Script {
    function run() external {
        uint256 deployerKey = vm.envUint("PRIVATE_KEY");
        address verifierAddr = vm.envAddress("VERIFIER_ADDRESS");

        CrystalVerifier verifier = CrystalVerifier(verifierAddr);

        // In production: read from tables.json generated by SDK
        // For now: generate test tables inline
        vm.startBroadcast(deployerKey);

        for (uint256 h = 0; h < 8; h++) {
            bytes memory tableData = new bytes(65536);
            // Placeholder: in production, load from file
            for (uint256 i = 0; i < 256; i++) {
                for (uint256 j = 0; j < 256; j++) {
                    tableData[i * 256 + j] =
                        bytes1(uint8((i * (h + 3) + j * (h + 7) + h * 17) % 256));
                }
            }
            verifier.initializeHead(h, tableData);
            console.log("Initialized head", h);
        }

        verifier.finalizeInitialization();
        console.log("Tables finalized. Contract ready.");

        vm.stopBroadcast();
    }
}
